### ISSUE TITLE
can any developer help explain what is ETH_SIGNATURE_KEY

### ISSUE THREAD

**Issue by liushmh** [flashbots/web3-flashbots#12]
There is ETH_SIGNATURE_KEY in sample.py

can anyone explain how it works?

**Comment by epheph** [comment]
https://github.com/flashbots/mev-relay-js#authentication

**Comment by im8s** [comment]
what is ETH_SIGNATURE_KEY？ 
where from ETH_SIGNATURE_KEY？

**Comment by epheph** [comment]
https://docs.flashbots.net/flashbots-auction/searchers/advanced/rpc-endpoint/#authentication
