### ISSUE TITLE
Bug diagnosed

### ISSUE THREAD

**Issue by Huge** [flashbots/web3-flashbots#21]
As per https://discord.com/channels/755466764501909692/795777653197635596/844259896999804949 we would like to fix `types.py` code to work with Python 3.8.x.

This was the necessary change in the beginning of the file:
```
from eth_account.account import Account
from web3.types import TxParams
from typing import TypedDict
import typing

FlashbotsBundleTx = TypedDict(
    "FlashbotsBundleTx",
    {
        "transaction": TxParams,
        "signer": Account,
    },
)

FlashbotsBundleRawTx = TypedDict(
    "FlashbotsBundleRawTx",
    {
        "signed_transaction": str,
    },
)

FlashbotsOpts = TypedDict(
    "FlashbotsOpts",
    {"minTimestamp": int, "maxTimestamp": int, "revertingTxHashes": typing.List[str]},
)```

Also would be nice to have `poetry install` mentioned in the Readme for semi-noobs like me who never got in touch with it before.

**Comment by N0K0** [comment]
PR created. Readme has `poetry install` in it already :D

**Comment by Huge** [comment]
> PR created. Readme has `poetry install` in it already :D

Ah, good eyes, sure that is great.

Other thing remaining unclear is in the `examples/simple.py` code what is the semantics of the `private_from` and `_to` @ https://github.com/flashbots/web3-flashbots/blob/c10ac3e790a44fa041e49f2229240bf6aedd9a52/examples/simple.py#L19 .
Would you consider to fit explanation of it into Readme or code comments?
