### ISSUE TITLE
Reformatting and cleanup of the code base

### ISSUE THREAD

**Issue by N0K0** [flashbots/web3-flashbots#3]
Hi! I've started on a cleanup of the code base located over here: https://github.com/N0K0/web3-flashbots
Its mainly based on good old PEP-8 and Black https://github.com/psf/black

Do the Flashbots organization have any opinions on codestyle++ :)
Other than that my goal is adding the missing signature header and clean up the demo files.

**Comment by gakonst** [comment]
This looks great to me, PRs welcome!

**Comment by N0K0** [comment]
Awesome! Hopefully done in the weekend :)

**Comment by N0K0** [comment]
Closing this issue, fixed in https://github.com/flashbots/web3-flashbots/pull/4
Not sure how the FB core/crew is organized, but I'm willing to help with the 0.2 upgrade too if needed!
