### ISSUE TITLE
Suggestion: automatic dependency checking

### ISSUE THREAD

**Issue by pmdaly** [flashbots/web3-flashbots#30]
A recent change in dependencies has broken the package's interaction with a key implicit component, Brownie.  One resolution is to add automatic dependency checking to catch these breaking changes before they effect users.  One such tool is [Dependabot](https://dependabot.com/).  

Im not sure how this would catch interactions with Brownie as it's not an explicit dependency but majority of Python solidity dev/deployment is managed with it.

**Comment by N0K0** [comment]
Great suggestion, seems like Poetry is supported!

**Comment by odysseus0** [comment]
If you define all the dependencies in Poetry it should resolve them all!
