### ISSUE TITLE
Simulating / sending bundle results in HTTP error 400.

### ISSUE THREAD

**Issue by avocadochicken** [flashbots/web3-flashbots#33]
Flashbots Relay is complaining if field 'gasPrice' is set. Removing line 91 in flashbots.py resolves this issue.

https://github.com/flashbots/web3-flashbots/blob/46c1cb08b250b964b51974384109e07cdf42eb98/flashbots/flashbots.py#L91

**Comment by alex-roytikh** [comment]
noticed this as well.

**Comment by zeroXbrock** [comment]
this is outdated; fixed in version 1.0.0
