### ISSUE TITLE
ImportError: cannot import name 'ModuleV2' from 'web3.module'

### ISSUE THREAD

**Issue by cattieinthere** [flashbots/web3-flashbots#38]
I use `web3 5.23.1`, `Python 3.9.6` and `GCC 9.3.0` on linux.

When trying to import the `flashbots` module:

> from flashbots import flashbot

This is the output:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.9/dist-packages/flashbots/__init__.py", line 9, in <module>
>     from .flashbots import Flashbots
>   File "/usr/local/lib/python3.9/dist-packages/flashbots/flashbots.py", line 5, in <module>
>     from web3.module import ModuleV2
> ImportError: cannot import name 'ModuleV2' from 'web3.module' (/usr/local/lib/python3.9/dist-packages/web3/module.py)

Maybe flashbots isn't compatible with the latest version of web3? Or what am I missing?

**Comment by patllc** [comment]
instead of import ModuleV2, import Module

**Comment by zeroXbrock** [comment]
@cattieinthere are you still having this issue?
