### ISSUE TITLE
Stuck reading the documentation example

### ISSUE THREAD

**Issue by cattieinthere** [flashbots/web3-flashbots#39]
In [this example](https://github.com/flashbots/web3-flashbots/blob/master/examples/simple.py), I'm stuck [here](https://github.com/flashbots/web3-flashbots/blob/master/examples/simple.py#L20):

> ETH_ACCOUNT_TO: LocalAccount = Account.from_key(os.environ.get("ETH_PRIVATE_TO"))

How could I possibly have the private key of the receiving address?

And also [here](https://github.com/flashbots/web3-flashbots/blob/master/examples/simple.py#L70), why should the `ETH_ACCOUNT_TO` sign the transaction and not, instead, the `ETH_ACCOUNT_FROM`?

**Comment by zeroXbrock** [comment]
yeah, this example was unclear. Fixed in #55
