### ISSUE TITLE
Support for greater web.py versions

### ISSUE THREAD

**Issue by unparalleled-js** [flashbots/web3-flashbots#45]
Hello Flashbots!

## Problem

The most recently released version of flashbots has a  `web.py` version requirement that is too low for the environment I need to run this package in (`<5.18.0,>=5.17.0`). My environment requires `web.py` >= `5.28.0`.

## Solution

It looks like this might already be fixed in the `master` branch of this repository via the changes I see in the `pyproject.toml` file.
Maybe a release is all that is needed?

## Extra

My situation requires I work with a released version of the package

**Comment by zeroXbrock** [comment]
`<5.18.0,>=5.17.0` doesn't make much sense, but the lib supports `web3 = ">=5.22.0, <6"`. You should be able to use web3 5.28 if you like. Just manually install it in your project.
