### ISSUE TITLE
sim error on eip1559 example when using Goerli network

### ISSUE THREAD

**Issue by tztlzspond** [flashbots/web3-flashbots#52]
I used the example as is but made some modification, including
1. Changing chainID to 5 for Goerli test network
2. Adding "w3.middleware_onion.inject(geth_poa_middleware, layer=0)" to resolve the POA chain error

However I still received the following error:
sim error {'code': -32000, 'message': 'missing trie node 4216c08cb01c7e93ab89e22710bff15671947a723d5bd3986bbf7d26262096c7 (path )'}

Also I keep getting "Bundle was not executed" message even when setting a higher gas price...anyone has the same issue?

**Comment by paulpou69** [comment]
I got the same error, did you find a solution?

**Comment by TabrisEth** [comment]
the simple example also has some error, i think it seems like not been tested..

**Comment by tztlzspond** [comment]
yes there were quite a few errors in the code sample. I think I've fixed most of them but couldn't seem to get these working. I have not found a solution so far unfortunately...

**Comment by zeroXbrock** [comment]
This should be fixed in #55. The example didn't do a good job of explaining how Goerli should work.
