### ISSUE TITLE
goerli testnet 400 Client Error: Bad Request for url

### ISSUE THREAD

**Issue by hongwei520** [flashbots/web3-flashbots#54]
I have an error when using the send_private_transaction method send_bundel is ok can someone tell me what is the problem。
![image](https://user-images.githubusercontent.com/39451921/168006701-3ae9c5fa-74cd-4d43-b141-3904968b130a.png)

code:
    bundle = {"signed_transaction": tx1_signed.rawTransaction}
    w3.flashbots.send_private_transaction(bundle)

**Comment by zeroXbrock** [comment]
@hongwei520 can you post your full code? (please use a [code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks))

**Comment by andrewnagata** [comment]
Looks like the relay url is being used for the http provider. The HTTP provider should be pointed to a node running mev-geth. The relay url is defined with the after the web3 instance like so:

```
w3 = Web3(HTTPProvider("http://10.0.1.68:8545")) #<--- HTTP Provider
flashbot(w3, FLASHBOTS_SIGNATURE, "https://relay-goerli.flashbots.net") #<--- Relay URL here
```

**Comment by cheikhToure** [comment]
I have the same error when calling the `send_private_transaction` function in the goerli network:

`400 Client Error: Bad Request for url: https://relay-goerli.flashbots.net/`.

The way i use it is:
```python
        tx_params = {'from': address, "maxFeePerGas": max_fee, "maxPriorityFeePerGas": max_priority_fee,
         "nonce": nonce, "chainId": chain.id, "type": 2}
        tx = my_contract.functions.my_function(...).buildTransaction(tx_params)
        tx_flashbots = {"signer": myaccount, "transaction": tx}
        sent_tx = w3.flashbots.send_private_transaction(tx_flashbots)
```

**Comment by hongwei520** [comment]
This method is not yet supported by the test network. Make a suggestion and print out detailed error information when reporting an error.

**Comment by xiaotiananan** [comment]
> FLASHBOTS_SIGNATURE

Have you solved this problem？

**Comment by zeroXbrock** [comment]
> Looks like the relay url is being used for the http provider. The HTTP provider should be pointed to a node running mev-geth. The relay url is defined with the after the web3 instance like so:
> 
> ```
> w3 = Web3(HTTPProvider("http://10.0.1.68:8545")) #<--- HTTP Provider
> flashbot(w3, FLASHBOTS_SIGNATURE, "https://relay-goerli.flashbots.net") #<--- Relay URL here
> ```

The provider url does not need to be an mev-geth node. It can be any provider.

Like @hongwei520 mentioned, `sendPrivateTransaction` (and `cancelPrivateTransaction`) are not implemented on goerli yet. Thank you @hongwei520 for the suggestion. This should be resolved once the relay team implements these methods on the goerli relay.
