### ISSUE TITLE
Support web3.py v6

### ISSUE THREAD

**Issue by zoey-t** [flashbots/web3-flashbots#75]
web3.py v6 has breaking changes. Currently flashbots only supports web3 (>=5.22.0,<6)

**Comment by BrokedTV** [comment]
async support too

**Comment by DaizzX** [comment]
I can't do anything with this because of the limit of web3 < 6...

**Comment by jeamick** [comment]
Probably worth looking at this for a starter: https://web3py.readthedocs.io/en/stable/v6_migration.html

**Comment by jiantaolmc** [comment]
when support web3.py v6, please

**Comment by josecyc** [comment]
I also require web3.py v6 for my project, is there a workaround for this?

**Comment by godofbeans** [comment]
For now, see #85, but yeah, I really can't do anything with this until there is web3 v6+ support.

**Comment by odysseus0** [comment]
Folks thanks a lot for the patience. Will push all the changes and get things updated early next week. All code ready. Just need to resolve some git issues.
