### ISSUE TITLE
install issues

### ISSUE THREAD

**Issue by siyangyuandegit** [flashbots/web3-flashbots#78]
when I try to execute poetry install I have got error:
Note: This error originates from the build backend, and is likely not a problem with poetry but with cytoolz (0.11.2) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "cytoolz (==0.11.2)"'.
how can i fix it ?

**Comment by siyangyuandegit** [comment]
/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c cytoolz/dicttoolz.c -o build/temp.macosx-10.9-universal2-cpython-311/cytoolz/dicttoolz.o
  cytoolz/dicttoolz.c:211:12: fatal error: 'longintrepr.h' file not found
    #include "longintrepr.h"
             ^~~~~~~~~~~~~~~
  1 error generated.
  error: command '/usr/bin/clang' failed with exit code 1
  

  at ~/Library/Application Support/pypoetry/venv/lib/python3.11/site-packages/poetry/installation/chef.py:147 in _prepare
      143│ 
      144│                 error = ChefBuildError("\n\n".join(message_parts))
      145│ 
      146│             if error is not None:
    → 147│                 raise error from None
      148│ 
      149│             return path
      150│ 
      151│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with cytoolz (0.11.2) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "cytoolz (==0.11.2)"'.
more info

**Comment by juansolana** [comment]
Where you able to solve this issue? I'm having the same one

**Comment by 0xSyntellect** [comment]
+1

**Comment by odysseus0** [comment]
Gonna push a new version that has everything updated and resolved. Thanks a lot for patience.
