### ISSUE TITLE
Continuous Send Bundle Transactions, the simulate goes to failed by "nonce too high" error

### ISSUE THREAD

**Issue by UselessXiaoYao** [flashbots/web3-flashbots#83]
Hi,
   When I write some test case, for example, 1st step, swap ETH to UNI, 2nd step approve uniswap router, then the 3rd step swap UNI back to ETH. I always meet "nonce too high" error when I do simulation of the approve transaction, **because the 1st step block number is same as the simulate block**, and the nonce to the block has not increased yet, but new transaction's nonce has to increase.
   So, do I have to do a delay to stagger this block? Or this is just a bug?

**Comment by odysseus0** [comment]
Would love to help you with the issue on our Discord if you can show the full code there.
