### ISSUE TITLE
flashbots 1.1.1 requires web3<6,>=5.22.0, but you have web3 6.13.0 which is incompatible

### ISSUE THREAD

**Issue by francestu96** [flashbots/web3-flashbots#85]
I'm using the last stable version of web3 (v6.13.0) but flashbots is incompatible with it and I receive the error:
**(AttributeError("'Flashbots' object has no attribute 'web3'"))**

While installing flashbots it with pip I receive the error: 
**ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
flashbots 1.1.1 requires web3<6,>=5.22.0, but you have web3 6.13.0 which is incompatible.**

**Comment by UselessXiaoYao** [comment]
go into flashbots.py, and modify all "self.web3" to "self.w3"

**Comment by godofbeans** [comment]
I just want to bump this as official web3 v6+ support would be INCREDIBLY helpful for those who appreciate less janky solutions. Thanks a ton

**Comment by odysseus0** [comment]
Gonna push all the changes to support v6. Thank you guys for the patience.

**Comment by mapping77** [comment]
> Gonna push all the changes to support v6 early next week. Thank you guys for the patience.

Thanks so much, v6 support will be really helpful!

**Comment by odysseus0** [comment]
https://github.com/flashbots/web3-flashbots/pull/87#issuecomment-2245800543
