### ISSUE TITLE
No longer able to run the example simple.py

### ISSUE THREAD

**Issue by josecyc** [flashbots/web3-flashbots#86]
A couple of days ago I was able to run the simple.py on GOERLI and on Mainnet, I did up to 4 transactions in a single bundle.
Not sure what happened but I'm now getting the following error during simulation:
`Simulation error {'code': -32000, 'message': 'err: %!w(<nil>); txhash 0x2a87221dda99210c637533057ebea8269bc33a87ebf52170bae7ad9b033f4be0'}`
My account has Goerli ETH, the RPC seems to run fine, I'm lost about what could've happened.

**Comment by josecyc** [comment]
Turns out I am able to actually use the mainnet for sending bundles. The issue was related to this particular day most likely because of the deprecation of Goerli so I think that example is not really going to work on Goerli for anyone anymore.

**Comment by jasonthewhale** [comment]
The simulation doesn't work, but flashbots builder is still running on goerli, so send bundle works.

**Comment by darkerego** [comment]
> The simulation doesn't work, but flashbots builder is still running on goerli, so send bundle works.

Is this still the case? I thought Goerli was had been shut down?

**Comment by odysseus0** [comment]
looking into it right now. thanks for flagging guys

**Comment by odysseus0** [comment]
Turned out to be an issue on the relay bakend. Right now Holesky is the one in best condition and the script works there. Will try to fix the backend issue and push a new example script that supports all networks.
